### ISSUE TITLE
`counts.py` stops working from time to time

### ISSUE THREAD

**Issue by zaikunzhang** [pdfo/pdfo.github.io#8]
```
Run python -m venv venv
Collecting condastats==0.2.[1](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:1)
  Downloading condastats-0.2.1-py3-none-any.whl (5.9 kB)
Collecting requests==2.28.1
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 2.5 MB/s eta 0:00:00
Collecting numpy>=1.16.5
  Downloading numpy-1.24.0-cp39-cp39-manylinux_2_17_x86_64.manylinux[20](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:21)14_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 23.8 MB/s eta 0:00:00
Collecting s3fs
  Downloading s3fs-2022.11.0-py3-none-any.whl (27 kB)
Collecting python-snappy
  Downloading python_snappy-0.6.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 KB [21](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:22).8 MB/s eta 0:00:00
Collecting pyarrow
  Downloading pyarrow-10.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.9/35.9 MB 73.6 MB/s eta 0:00:00
Collecting dask[dataframe]
  Downloading dask-20[22](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:23).12.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 104.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 25.7 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 46.4 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 KB 49.5 MB/s eta 0:00:00
Collecting cloudpickle>=1.1.1
  Downloading cloudpickle-2.2.0-py3-none-any.whl (25 kB)
Collecting fsspec>=0.6.0
  Downloading fsspec-2022.11.0-py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 KB 48.4 MB/s eta 0:00:00
Collecting packaging>=20.0
  Downloading packaging-22.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 KB 16.1 MB/s eta 0:00:00
Collecting toolz>=0.8.2
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 KB 18.2 MB/s eta 0:00:00
Collecting pyyaml>=5.3.1
  Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 KB 100.6 MB/s eta 0:00:00
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 37.9 MB/s eta 0:00:00
Collecting partd>=0.3.10
  Downloading partd-1.3.0-py3-none-any.whl (18 kB)
Collecting pandas>=1.0
  Downloading pandas-1.5.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 112.5 MB/s eta 0:00:00
Collecting aiobotocore~=2.4.0
  Downloading aiobotocore-2.4.2-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 KB 22.0 MB/s eta 0:00:00
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Downloading aiohttp-3.8.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 117.9 MB/s eta 0:00:00
Collecting botocore<1.27.60,>=1.27.59
  Downloading botocore-1.27.59-py3-none-any.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 143.1 MB/s eta 0:00:00
Collecting aioitertools>=0.5.1
  Downloading aioitertools-0.11.0-py3-none-any.whl ([23](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:24) kB)
Collecting wrapt>=1.10.10
  Downloading wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 KB 28.9 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (264 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 68.7 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 39.5 MB/s eta 0:00:00
Collecting attrs>=17.3.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 KB 22.2 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 52.4 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting python-dateutil>=2.8.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl ([24](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:25)7 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 66.7 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2022.7-py2.py3-none-any.whl (499 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 KB 99.7 MB/s eta 0:00:00
Collecting locket
  Downloading locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Collecting typing_extensions>=4.0
  Downloading typing_extensions-4.4.0-py3-none-any.whl ([26](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:27) kB)
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, python-snappy, wrapt, urllib3, typing_extensions, toolz, six, pyyaml, packaging, numpy, multidict, locket, jmespath, idna, fsspec, frozenlist, cloudpickle, click, charset-normalizer, certifi, attrs, async-timeout, yarl, requests, python-dateutil, pyarrow, partd, aiosignal, aioitertools, pandas, dask, botocore, aiohttp, aiobotocore, s3fs, condastats
Successfully installed aiobotocore-2.4.2 aiohttp-3.8.3 aioitertools-0.11.0 aiosignal-1.3.1 async-timeout-4.0.2 attrs-22.2.0 botocore-1.[27](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:28).59 certifi-2022.12.7 charset-normalizer-2.1.1 click-8.1.3 cloudpickle-2.2.0 condastats-0.2.1 dask-2022.12.1 frozenlist-1.3.3 fsspec-2022.11.0 idna-3.4 jmespath-1.0.1 locket-1.0.0 multidict-6.0.3 numpy-1.24.0 packaging-22.0 pandas-1.5.2 partd-1.3.0 pyarrow-10.0.1 python-dateutil-2.8.2 python-snappy-0.6.1 pytz-2022.7 pyyaml-6.0 requests-2.[28](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:29).1 s3fs-2022.11.0 six-1.16.0 toolz-0.12.0 typing_extensions-4.4.0 urllib3-1.26.13 wrapt-1.14.1 yarl-1.8.2
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the '/home/runner/work/pdfo.github.io/pdfo.github.io/venv/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/home/runner/work/pdfo.github.io/pdfo.github.io/static/scripts/stats/counts.py", line 67, in <module>
    'github': github_count('pdfo', 'pdfo', sys.argv[4]),
  File "/home/runner/work/pdfo.github.io/pdfo.github.io/static/scripts/stats/counts.py", line [53](https://github.com/pdfo/pdfo.github.io/actions/runs/3762027767/jobs/6394320199#step:5:54), in github_count
    download_count = sum(sum(map(lambda d: d['download_count'], release['assets'])) for release in r.json())
  File "/home/runner/work/pdfo.github.io/pdfo.github.io/static/scripts/stats/counts.py", line 53, in <genexpr>
    download_count = sum(sum(map(lambda d: d['download_count'], release['assets'])) for release in r.json())
TypeError: string indices must be integers
Error: Process completed with exit code 1.
```

**Comment by ragonneau** [comment]
Could you please give me the link to a failed run in the Actions? Thank you 😄

**Comment by zaikunzhang** [comment]
https://github.com/pdfo/pdfo.github.io/actions/runs/3778014524
